; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Transmitter"
#define MyAppVersion "1.0.4.0"
#define MyAppPublisher "Jonathan Beckett"
#define MyAppURL "https://virtualflight.online"
#define MyAppExeName "Transmitter.exe"

; Build output (repo-relative)
#define BuildOutputDir "..\bin\Release"
#define SetupIconPath "..\virtualflightonline128x128.ico"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{2435F882-5856-40D6-ABB7-B9ECF3A37E06}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=commandline
OutputDir={#SourcePath}
OutputBaseFilename=transmitter_1.0.4.0
SetupIconFile={#SetupIconPath}
Compression=lzma
SolidCompression=yes
WizardStyle=modern
UsePreviousAppDir=false


[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]

; Runtime-only payload: the app + its runtime DLLs.
; Excludes dev artifacts (PDB) and documentation files (XML), plus ClickOnce files.
Source: "{#BuildOutputDir}\Transmitter.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#BuildOutputDir}\Transmitter.exe.config"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#BuildOutputDir}\*.dll"; DestDir: "{app}"; Flags: ignoreversion

; Optional external manifest (some builds may not produce this file)
#ifexist "{#BuildOutputDir}\Transmitter.exe.manifest"
Source: "{#BuildOutputDir}\Transmitter.exe.manifest"; DestDir: "{app}"; Flags: ignoreversion
#endif

; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent